'use client';

import {
  ArrowUpRight,
  Bot,
  Settings,
  User,
  Sparkles,
  X,
  Send,
  Save,
  AlertCircle,
  AlertTriangle,
  Edit2,
  Edit,
  Link,
  Type,
  Search,
  Image,
  Lock,
  Info,
  Plus,
  Trash,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  Star,
  Settings2,
  Key,
  Layout,
  Tag,
  Upload,
  Box,
  ChevronDown,
  LogOut,
  Loader,
  FileText,
  Eye,
  EyeOff,
  Download,
  Check,
  Copy,
  Shield,
  Calendar,
  Clock,
  Palette,
  LayoutGrid,
  BookOpen,
  Filter,
  ChevronRight,
  List,
  LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// Icon name mapping - supports both PascalCase and camelCase
const iconMap: Record<string, LucideIcon> = {
  ArrowUpRight,
  arrowUpRight: ArrowUpRight,
  Bot,
  bot: Bot,
  Settings,
  settings: Settings,
  User,
  user: User,
  Sparkles,
  sparkles: Sparkles,
  X,
  x: X,
  Send,
  send: Send,
  Save,
  save: Save,
  AlertCircle,
  alertCircle: AlertCircle,
  AlertTriangle,
  alertTriangle: AlertTriangle,
  Edit2,
  edit2: Edit2,
  Edit,
  edit: Edit,
  Link,
  link: Link,
  Type,
  type: Type,
  Search,
  search: Search,
  Image,
  image: Image,
  Lock,
  lock: Lock,
  Info,
  info: Info,
  Plus,
  plus: Plus,
  Trash,
  trash: Trash,
  ArrowUp,
  arrowUp: ArrowUp,
  ArrowDown,
  arrowDown: ArrowDown,
  ArrowLeft,
  arrowLeft: ArrowLeft,
  Star,
  star: Star,
  Key,
  key: Key,
  Layout,
  layout: Layout,
  Tag,
  tag: Tag,
  Upload,
  upload: Upload,
  Box,
  box: Box,
  ChevronDown,
  chevronDown: ChevronDown,
  LogOut,
  logOut: LogOut,
  Loader,
  loader: Loader,
  FileText,
  fileText: FileText,
  Eye,
  eye: Eye,
  EyeOff,
  eyeOff: EyeOff,
  Download,
  download: Download,
  Check,
  check: Check,
  Copy,
  copy: Copy,
  Shield,
  shield: Shield,
  Calendar,
  calendar: Calendar,
  Clock,
  clock: Clock,
  Palette,
  palette: Palette,
  LayoutGrid,
  layoutGrid: LayoutGrid,
  BookOpen,
  bookOpen: BookOpen,
  Filter,
  filter: Filter,
  ChevronRight,
  chevronRight: ChevronRight,
  List,
  list: List,
  Settings2,
  settings2: Settings2,
};

export type IconName = keyof typeof iconMap;

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 16, className }: IconProps) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return <span className={className}>•</span>;
  }

  return <IconComponent size={size} className={cn(className)} />;
}

export default Icon;

